example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist , show_xml, show_json, show_json_by_id, show_xml_by_id, register, login_user,logout_user, show_wishlist_ajax, submit_ajax

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'), 
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name= 'show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/submit', submit_ajax, name='submit_ajax'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

wishlist/forms.py
from pyexpat import model
from django.forms import ModelForm
from wishlist.models import BarangWishlist

class WishlistFormAjax(ModelForm):
    class Meta:
        model = BarangWishlist
        fields = ['nama_barang','harga_barang','deskripsi']

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from urllib import request
from django.shortcuts import render
from wishlist.models import BarangWishlist

from django.http import HttpResponse
from django.core import serializers

from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

from django.contrib.auth import authenticate, login
from django.contrib.auth import logout

from django.contrib.auth.decorators import login_required

import datetime
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse

from wishlist.forms import WishlistFormAjax

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Dipa Alhaza',
        'last_login': request.COOKIES['last_login'],
}
    return render(request, "wishlist.html",context)

@login_required(login_url='/wishlist/login')
def show_wishlist_ajax(request):
    context = {
        'nama': 'Dipa Alhaza',
        'last_login': request.COOKIES.get('last_login'),
    }
    return render(request, "wishlist_ajax.html", context)

@login_required(login_url='/wishlist/login')
def submit_ajax(request):
    if (request.method == 'POST'):
        data = {}
        form = WishlistFormAjax(request.POST or None)
        if (form.is_valid()):
            nama_barang = form.cleaned_data['nama_barang']
            harga_barang = form.cleaned_data['harga_barang']
            deskripsi = form.cleaned_data['deskripsi']
            new_wishlist = BarangWishlist.objects.create(nama_barang=nama_barang, harga_barang=harga_barang, deskripsi=deskripsi)
            data["nama_barang"] = nama_barang
            data["harga_barang"] = harga_barang
            data["deskripsi"] = deskripsi
            return JsonResponse(data)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>



<body>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Tutorial PBP</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href="{% url 'wishlist:login' %}">Tugas wishlist</a>
        </div>
      </div>
    </div>
  </nav>
  {% block content %}
  <h1>Testing</h1>
  {% endblock content %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>

    
{% block content %}
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-light" href="#">User login : {{request.user}}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link text-light" href="{% url 'wishlist:logout' %}">logout</a>
        <a class="nav-link text-light" href="{% url 'wishlist:show_wishlist_ajax' %}">Ajax Form</a>
      </div>
    </div>
  </div>
</nav>
<br>

<p class="h5">Nama: {{nama}}</p>
<br>
<br>

    
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}

<table class="table table-striped">
  <thead>
    <tr class="bg-dark">
      <th scope="col" class="text-light">Nomor</th>
      <th scope="col"class="text-light">Nama Barang</th>
      <th scope="col"class="text-light">Harga Barang</th>
      <th scope="col"class="text-light">Deskripsi</th>
    </tr>
  </thead>
  <tbody>
    {% for barang in list_barang %}
    <tr>
      <th scope="row">{{barang.id}}</th>
      <td>{{barang.nama_barang}}</td>
      <td>{{barang.harga_barang}}</td>
      <td>{{barang.deskripsi}}</td>
    </tr>
    {% endfor %}
  </tbody>

</table>

<h5 class="text-center">Sesi terakhir login: {{ last_login }}</h5>


{% endblock content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

wishlist/templates/wishlist_ajax.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ajax</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>

    
{% block content %}
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-light" href="#">User login : {{request.user}}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link text-light" href="{% url 'wishlist:logout' %}">logout</a>
        <a class="nav-link text-light" href="{% url 'wishlist:show_wishlist' %}">Wishlist</a>
      </div>
    </div>
  </div>
</nav>
<br>

<p class="h5">Nama: {{nama}}</p>
<br>
<br>

    
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}

<table class="table table-striped" id="table">
  <thead>
    <tr class="bg-dark">
      <th scope="col"class="text-light">Nama Barang</th>
      <th scope="col"class="text-light">Harga Barang</th>
      <th scope="col"class="text-light">Deskripsi</th>
    </tr>
  </thead>
  <tbody id="body-table">
    
  </tbody>

</table>

<h5 class="text-center">Sesi terakhir login: {{ last_login }}</h5>

<div class="w-50">
    <form id="form"" >  
        {% csrf_token %}  
            <!-- {{ form.as_table }}   -->
            <!-- {{ form.as_p }}  -->
            <div class="d-flex flex-column w-50 p-5">
                <div class="d-flex justify-content-between align-items-center">
                    <label class="m-2 p-2">Nama Barang</label>
                    <input type="text" name="nama_barang">
                    
                </div>
                <div class="d-flex justify-content-between align-items-center">
                    <label class="m-2 p-2">Harga Barang</label>
                    <input type="number" name="harga_barang">
                </div>
    
                <div class="d-flex justify-content-between align-items-center">
                    <label class="m-2 p-2">Deksripsi</label>
                    <input type="text" name="deskripsi">
                    
                </div>
                <input type="submit" class="btn btn-dark m-2 text-center"></input>
            </div>   
       
    </form>
</div>

{% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>

const table = document.getElementById('body-table')

$(document).ready(() => {
  $.get('/wishlist/json', (wishlists) => {
    wishlists.forEach((wishlist) => {
      $('#body-table').append(`
        <tr class="item-table-row">
          <td class="item-table-cell">${wishlist.fields.nama_barang}</td>
          <td class="item-table-cell">${wishlist.fields.harga_barang}</td>
          <td class="item-table-cell">${wishlist.fields.deskripsi}</td>
        </tr>
      `)
    })
  })
  
  $('#form').submit((e) => {
    e.preventDefault();
    $.ajax({
      url: '/wishlist/ajax/submit',
      type: 'POST',
      dataType: 'json',
      data: $('#form').serialize(),
      success: (resp) => {
        // console.log(resp)
        $('#body-table').append(`
          <tr class="item-table-row">
            <td class="item-table-cell">${resp.nama_barang}</td>
            <td class="item-table-cell">${resp.harga_barang}</td>
            <td class="item-table-cell">${resp.deskripsi}</td>
          </tr>
        `)
      },
    })
  })
})
</script>
</body>
</html>